services:
  dns-updater:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    configs:
      - config
    secrets:
      - gcp_service_account
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug

secrets:
  gcp_service_account:
    file: serviceaccount.json
configs:
  config:
    file: config.yaml
